# Generated by Django 4.1.7 on 2023-03-09 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookShop', '0002_book_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publisher_name',
            field=models.CharField(max_length=50),
        ),
    ]
